# Generated by Django 6.0.7 on 2026-07-08 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dias_para_primer_riego', models.IntegerField()),
                ('dias_para_primera_poda', models.IntegerField()),
                ('dias_para_inicio_cosecha', models.IntegerField()),
                ('ciclo_de_vida_total', models.IntegerField()),
                ('frecuencia_riego', models.IntegerField()),
                ('frecuencia_poda', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LoteCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_lote', models.CharField(max_length=100)),
                ('fecha_plantacion', models.DateField()),
                ('estado', models.CharField(choices=[('CRECIMIENTO', 'En crecimiento'), ('COSECHA', 'En cosecha'), ('TERMINADO', 'Terminado')], default='CRECIMIENTO', max_length=50)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.cultivo')),
            ],
        ),
        migrations.CreateModel(
            name='TareaProgramada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tarea', models.CharField(choices=[('RIEGO', 'Riego'), ('PODA', 'Poda'), ('FERTILIZACION', 'Fertilización'), ('COSECHA', 'Cosecha')], max_length=50)),
                ('fecha_programada', models.DateField()),
                ('completada', models.BooleanField(default=False)),
                ('lote_cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.lotecultivo')),
            ],
        ),
    ]
