# Generated by Django 6.0.7 on 2026-07-08 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cama', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('disponibilidad', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADA', 'Ocupada')], default='DISPONIBLE', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dias_para_primer_riego', models.IntegerField()),
                ('dias_para_primera_poda', models.IntegerField()),
                ('dias_para_primer_fertilizacion', models.IntegerField(default=0)),
                ('dias_para_inicio_cosecha', models.IntegerField()),
                ('ciclo_de_vida_total', models.IntegerField()),
                ('frecuencia_riego', models.IntegerField(default=0)),
                ('frecuencia_poda', models.IntegerField(default=0)),
                ('frecuencia_fertilizacion', models.IntegerField(default=0)),
                ('frecuencia_cosecha', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('FERTILIZANTE', 'Fertilizante'), ('PLAGUICIDA', 'Plaguicida'), ('SEMILLA', 'Semilla'), ('SUSTRATO', 'Sustrato'), ('OTRO', 'Otro')], default='-----', max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cantidad_disponible', models.FloatField()),
                ('cantidad_minima', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Invernadero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=200)),
                ('capacidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoteCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_lote', models.CharField(max_length=100)),
                ('fecha_plantacion', models.DateField()),
                ('estado', models.CharField(choices=[('CRECIMIENTO', 'En crecimiento'), ('COSECHA', 'En cosecha'), ('TERMINADO', 'Terminado')], default='CRECIMIENTO', max_length=50)),
                ('cama', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cultivos.cama')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.cultivo')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoInsumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_insumo', models.CharField(choices=[('FERTILIZANTE', 'Fertilizante'), ('PLAGUICIDA', 'Plaguicida'), ('SEMILLA', 'Semilla'), ('SUSTRATO', 'Sustrato'), ('OTRO', 'Otro')], max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('unidad_medida', models.CharField(choices=[('KG', 'Kilogramos'), ('L', 'Litros'), ('UNIDAD', 'Unidad'), ('BULTOS', 'Bultos')], max_length=50)),
                ('lote', models.CharField(blank=True, max_length=100, null=True)),
                ('proveedor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalogo_insumos', to='cultivos.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='TareaProgramada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tarea', models.CharField(choices=[('RIEGO', 'Riego'), ('PODA', 'Poda'), ('FERTILIZACION', 'Fertilización'), ('COSECHA', 'Cosecha')], max_length=50)),
                ('fecha_programada', models.DateField()),
                ('completada', models.BooleanField(default=False)),
                ('insumo_utilizado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cultivos.insumo')),
                ('lote_cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.lotecultivo')),
            ],
        ),
        migrations.CreateModel(
            name='UsoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis_por_cama', models.FloatField()),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.cultivo')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.insumo')),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('invernadero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.invernadero')),
            ],
        ),
        migrations.AddField(
            model_name='cama',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.zona'),
        ),
    ]
