# Generated by Django 6.0.7 on 2026-07-23 00:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cantidad_camas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoAgroquimicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoInsumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_insumo', models.CharField(choices=[('FERTILIZANTE', 'Fertilizante'), ('SEMILLA', 'Semilla'), ('SUSTRATO', 'Sustrato'), ('OTRO', 'Otro')], max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('unidad_medida', models.CharField(choices=[('KG', 'Kilogramos'), ('L', 'Litros'), ('UNIDAD', 'Unidad'), ('BULTOS', 'Bultos')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoPlagas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comun', models.CharField(max_length=100)),
                ('nombre_cientifico', models.CharField(blank=True, max_length=100)),
                ('categoria', models.CharField(choices=[('INSECTO', 'insecto'), ('ACARO', 'ácaro'), ('HONGO', 'hongo'), ('BACTERIA', 'bacteria'), ('VIRUS', 'virus')], max_length=80)),
                ('descripcion_sintomas', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cultivo', models.CharField(choices=[('TIERRA', 'Tierra'), ('HIDROPONIA', 'Hidroponia'), ('MIXTO', 'Tierra e hidroponia')])),
                ('nombre', models.CharField(max_length=100)),
                ('dias_para_primera_poda', models.IntegerField(default=0)),
                ('dias_para_inicio_cosecha', models.IntegerField(default=0)),
                ('ciclo_vida_total', models.IntegerField(default=0)),
                ('frecuencia_poda', models.IntegerField(default=0)),
                ('frecuencia_cosecha', models.IntegerField(default=0)),
                ('inicio_cultivo', models.IntegerField(default=0)),
                ('fecha_trasplante', models.IntegerField(default=0)),
                ('inicio_tutorado', models.IntegerField(default=0)),
                ('dias_para_tutorado', models.IntegerField(default=0)),
                ('dias_para_primer_riego', models.IntegerField(default=0)),
                ('frecuencia_riego', models.IntegerField(default=0)),
                ('dias_para_primer_fertilizacion', models.IntegerField(default=0)),
                ('frecuencia_fertilizacion', models.IntegerField(default=0)),
                ('ph_optimo_min', models.IntegerField(default=0)),
                ('ph_optimo_max', models.IntegerField(default=0)),
                ('conductividad_electrica_optima', models.IntegerField(default=0)),
                ('tiempo_riego_minutos', models.IntegerField(default=0)),
                ('tiempo_espera_minutos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Invernadero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=200)),
                ('cantidad_bloques', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cama', models.IntegerField(default=0)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('disponibilidad', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADA', 'Ocupada')], default='DISPONIBLE', max_length=50)),
                ('bloque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cultivos.bloque')),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(choices=[('FERTILIZANTE', 'Fertilizante'), ('SEMILLA', 'Semilla'), ('SUSTRATO', 'Sustrato'), ('OTRO', 'Otro')], default='-----', max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cantidad_disponible', models.FloatField()),
                ('cantidad_minima', models.FloatField(default=0.0)),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.catalogoinsumos')),
                ('proveedor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalogo_insumos', to='cultivos.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Fumigacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aplicacion', models.DateTimeField(default=datetime.datetime(2026, 7, 23, 0, 1, 53, 567392, tzinfo=datetime.timezone.utc))),
                ('dosis', models.IntegerField(default=0, help_text='expresado en gramos o mililitros')),
                ('gasto_agua', models.FloatField(help_text='Litros de agua totales preparados')),
                ('intervalo_seguridad', models.IntegerField(help_text='Días obligatorios que deben pasar antes de poder cosechar')),
                ('plaga_objetivo', models.CharField(max_length=100)),
                ('aplicador', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fumigaciones', to='cultivos.bloque')),
                ('compuesto_aplicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.insumo')),
            ],
        ),
        migrations.AddField(
            model_name='bloque',
            name='invernadero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='cultivos.invernadero'),
        ),
        migrations.CreateModel(
            name='LoteCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_lote', models.CharField(max_length=100)),
                ('fecha_plantacion', models.DateField()),
                ('tipo_sustrato_sugerido', models.CharField(choices=[('FIBRA_COCO', 'Fibra de coco'), ('PERLITA', 'Perlita'), ('TEZONTLE', 'Tezontle'), ('VERMICULITA', 'Vermiculita'), ('LANA_ROCA', 'Lana de roca'), ('ARCILLA_EXPANDIDA', 'Arcilla expandida'), ('TURBA', 'Turba'), ('RAIZ_FLOTANTE', 'Sin sustrato')])),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.bloque')),
                ('cama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.cama')),
                ('invernadero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.invernadero')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.cultivo')),
            ],
        ),
        migrations.CreateModel(
            name='TareaProgramada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateField()),
                ('completada', models.BooleanField(default=False)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('duracion_tarea', models.DurationField(blank=True, null=True)),
                ('bloque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cultivos.bloque')),
                ('cama', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cultivos.cama')),
                ('insumo_utilizado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cultivos.insumo')),
                ('invernadero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cultivos.invernadero')),
                ('lote_cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lote_cultivo', to='cultivos.lotecultivo')),
                ('tipo_tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_tarea', to='cultivos.lotecultivo')),
            ],
        ),
        migrations.CreateModel(
            name='UsoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis_por_cama', models.FloatField()),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.cultivo')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.insumo')),
            ],
        ),
    ]
