# Generated by Django 6.0.7 on 2026-07-09 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogoinsumos',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='catalogoinsumos',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='insumo',
            name='lote',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='proveedor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalogo_insumos', to='cultivos.proveedor'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='cultivos.catalogoinsumos'),
        ),
    ]
