# Generated by Django 6.0.7 on 2026-07-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivo',
            name='dias_para_primer_fertilizacion',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='frecuencia_cosecha',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='frecuencia_fertilizacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='frecuencia_poda',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='frecuencia_riego',
            field=models.IntegerField(default=0),
        ),
    ]
