# Generated by Django 6.0.7 on 2026-07-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0002_cultivo_dias_para_primer_fertilizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivo',
            name='dias_para_primer_fertilizacion',
            field=models.IntegerField(default=0),
        ),
    ]
