# Generated by Django 6.0.7 on 2026-07-09 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0002_remove_catalogoinsumos_lote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogoinsumos',
            name='nombre',
            field=models.CharField(default='nada', max_length=100),
            preserve_default=False,
        ),
    ]
