# Generated by Django 6.0.7 on 2026-07-08 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0003_alter_cultivo_dias_para_primer_fertilizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cama', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('disponibilidad', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADA', 'Ocupada')], default='DISPONIBLE', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Invernadero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=200)),
                ('capacidad', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='lotecultivo',
            name='cama',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cultivos.cama'),
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('invernadero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.invernadero')),
            ],
        ),
        migrations.AddField(
            model_name='cama',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.zona'),
        ),
    ]
