# Generated by Django 6.0.7 on 2026-07-23 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0005_alter_fumigacion_fecha_aplicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fumigacion',
            name='fecha_aplicacion',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 23, 0, 8, 16, 863105, tzinfo=datetime.timezone.utc)),
        ),
    ]
