# Generated by Django 6.0.7 on 2026-07-09 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0005_perfilempleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilempleado',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='AsistenciaDiaria',
        ),
        migrations.DeleteModel(
            name='PerfilEmpleado',
        ),
    ]
