# Generated by Django 6.0.7 on 2026-07-13 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0006_remove_perfilempleado_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareaprogramada',
            name='cama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cultivos.cama'),
        ),
        migrations.AddField(
            model_name='tareaprogramada',
            name='invernadero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cultivos.invernadero'),
        ),
        migrations.AddField(
            model_name='tareaprogramada',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cultivos.zona'),
        ),
    ]
