# Generated by Django 6.0.7 on 2026-07-16 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0009_tareaprogramada_cama_tareaprogramada_invernadero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotecultivo',
            name='sistema_cultivo',
            field=models.CharField(choices=[('HIDROPONICO', 'Hidroponía (Sustrato / Solución Recirculante)'), ('TRADICIONAL', 'Tradicional (Suelo / Tierra)')], default='TRADICIONAL', max_length=20),
        ),
    ]
