# Generated by Django 6.0.7 on 2026-07-23 02:02

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0010_cultivo_requiere_poda_cultivo_requiere_tutorado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('operario', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='cultivo',
            old_name='dias_para_primer_fertilizacion',
            new_name='frecuencia_tutorado',
        ),
        migrations.RenameField(
            model_name='cultivo',
            old_name='dias_para_primer_riego',
            new_name='primer_fertilizacion',
        ),
        migrations.RenameField(
            model_name='cultivo',
            old_name='dias_para_primera_poda',
            new_name='primer_riego',
        ),
        migrations.RenameField(
            model_name='cultivo',
            old_name='dias_para_tutorado',
            new_name='primera_poda',
        ),
        migrations.RemoveField(
            model_name='cultivo',
            name='tiempo_espera_minutos',
        ),
        migrations.RemoveField(
            model_name='cultivo',
            name='tiempo_riego_minutos',
        ),
        migrations.AddField(
            model_name='tareaprogramada',
            name='operario',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fumigacion',
            name='fecha_aplicacion',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 23, 2, 1, 58, 131179, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='lotecultivo',
            name='tipo_sustrato_sugerido',
            field=models.CharField(blank=True, choices=[('FIBRA_COCO', 'Fibra de coco'), ('PERLITA', 'Perlita'), ('TEZONTLE', 'Tezontle'), ('VERMICULITA', 'Vermiculita'), ('LANA_ROCA', 'Lana de roca'), ('ARCILLA_EXPANDIDA', 'Arcilla expandida'), ('TURBA', 'Turba'), ('RAIZ_FLOTANTE', 'Sin sustrato')], null=True),
        ),
        migrations.AlterField(
            model_name='tareaprogramada',
            name='tipo_tarea',
            field=models.CharField(choices=[('SIEMBRA', 'Siembra'), ('RIEGO', 'Riego'), ('FUMIGACION', 'Fumigación'), ('FERTILIZACION', 'Fertilización'), ('PODA', 'Poda / Deshije'), ('TUTORADO', 'Tutorado / Amarre'), ('TRASPLANTE', 'Trasplante'), ('COSECHA', 'Cosecha')], max_length=20),
        ),
    ]
