# Generated by Django 6.0.7 on 2026-07-16 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0010_lotecultivo_sistema_cultivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareaprogramada',
            name='usuario_asignado',
        ),
    ]
