# Generated by Django 6.0.7 on 2026-07-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0011_remove_tareaprogramada_usuario_asignado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotecultivo',
            name='sistema_cultivo',
            field=models.CharField(choices=[('HIDROPONICO', 'Hidroponía (Sustrato / Solución Recirculante)'), ('TRADICIONAL', 'Tradicional (Suelo / Tierra)'), ('MIXTO', 'Apto para ambos (Hidroponía y Tradicional)')], default='TRADICIONAL', max_length=20),
        ),
    ]
