# Generated by Django 6.0.7 on 2026-07-16 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0012_alter_lotecultivo_sistema_cultivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lotecultivo',
            old_name='id_lote',
            new_name='lote_cultivo',
        ),
    ]
