# Generated by Django 6.0.7 on 2026-07-23 02:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0012_alter_fumigacion_fecha_aplicacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cultivo',
            old_name='dias_para_inicio_cosecha',
            new_name='primera_cosecha',
        ),
        migrations.AlterField(
            model_name='fumigacion',
            name='fecha_aplicacion',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 23, 2, 3, 51, 873480, tzinfo=datetime.timezone.utc)),
        ),
    ]
