# Generated by Django 6.0.7 on 2026-07-23 02:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0013_rename_dias_para_inicio_cosecha_cultivo_primera_cosecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivo',
            name='dias_para_trasplante',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='frecuencia_limpieza_filtros',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='frecuencia_monitoreo_ph_ce',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='requiere_trasplante',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fumigacion',
            name='fecha_aplicacion',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 23, 2, 22, 44, 922184, tzinfo=datetime.timezone.utc)),
        ),
    ]
