# Generated by Django 6.0.7 on 2026-07-16 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0013_rename_id_lote_lotecultivo_lote_cultivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lotecultivo',
            old_name='lote_cultivo',
            new_name='id_lote',
        ),
    ]
