# Generated by Django 6.0.7 on 2026-07-23 03:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0014_cultivo_dias_para_trasplante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultivo',
            name='frecuencia_limpieza_filtros',
        ),
        migrations.AddField(
            model_name='lotecultivo',
            name='estado',
            field=models.CharField(choices=[('GERMINACION', 'En Germinación / Semillero'), ('PREPARACION', 'Cama en Preparación'), ('PRODUCCION', 'En Producción (Trasplantado/En Cama)'), ('FINALIZADO', 'Ciclo Finalizado'), ('CANCELADO', 'Lote Cancelado')], default='GERMINACION', max_length=20),
        ),
        migrations.AlterField(
            model_name='fumigacion',
            name='fecha_aplicacion',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 23, 3, 18, 27, 662280, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tareaprogramada',
            name='tipo_tarea',
            field=models.CharField(choices=[('ACONDICIONAMIENTO', 'Acondicionamiento de camas'), ('SIEMBRA', 'Siembra'), ('RIEGO', 'Riego'), ('FERTILIZACION', 'Fertilización'), ('PODA', 'Poda / Deshije'), ('TUTORADO', 'Tutorado / Amarre'), ('TRASPLANTE', 'Trasplante'), ('MONITOREO', 'Monitoreo de pH y CE'), ('COSECHA', 'Cosecha')], max_length=20),
        ),
    ]
