# Generated by Django 6.0.7 on 2026-07-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0014_rename_lote_cultivo_lotecultivo_id_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareaprogramada',
            name='tipo_tarea',
            field=models.CharField(choices=[('RIEGO', 'Riego'), ('PODA', 'Poda'), ('FERTILIZACION', 'Fertilización'), ('FUMIGACION', 'Fumigación'), ('COSECHA', 'Cosecha')], max_length=50),
        ),
    ]
