# Generated by Django 6.0.7 on 2026-07-23 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0015_remove_cultivo_frecuencia_limpieza_filtros_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultivo',
            name='inicio_cultivo',
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='fecha_trasplante',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fumigacion',
            name='fecha_aplicacion',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 23, 4, 56, 10, 400687, tzinfo=datetime.timezone.utc)),
        ),
    ]
