# Generated by Django 6.0.7 on 2026-07-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0015_alter_tareaprogramada_tipo_tarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivo',
            name='dias_para_primer_fumigacion',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cultivo',
            name='frecuencia_fumigacion',
            field=models.IntegerField(default=0),
        ),
    ]
