# Generated by Django 6.0.7 on 2026-07-23 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0016_remove_cultivo_inicio_cultivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultivo',
            name='inicio_tutorado',
        ),
        migrations.RemoveField(
            model_name='cultivo',
            name='primer_fertilizacion',
        ),
        migrations.RemoveField(
            model_name='cultivo',
            name='primer_riego',
        ),
        migrations.RemoveField(
            model_name='cultivo',
            name='primera_poda',
        ),
        migrations.AlterField(
            model_name='fumigacion',
            name='fecha_aplicacion',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 23, 5, 14, 21, 821716, tzinfo=datetime.timezone.utc)),
        ),
    ]
