# Generated by Django 6.0.7 on 2026-07-17 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0016_cultivo_dias_para_primer_fumigacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotecultivo',
            name='zona',
        ),
        migrations.RemoveField(
            model_name='tareaprogramada',
            name='zona',
        ),
        migrations.RemoveField(
            model_name='cama',
            name='zona',
        ),
        migrations.RenameField(
            model_name='invernadero',
            old_name='capacidad',
            new_name='cantidad_bloques',
        ),
        migrations.AlterField(
            model_name='cama',
            name='numero_cama',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cantidad_camas', models.IntegerField(default=0)),
                ('invernadero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.invernadero')),
            ],
        ),
        migrations.AddField(
            model_name='cama',
            name='bloque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cultivos.bloque'),
        ),
        migrations.AddField(
            model_name='lotecultivo',
            name='bloque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cultivos.bloque'),
        ),
        migrations.AddField(
            model_name='tareaprogramada',
            name='bloque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cultivos.bloque'),
        ),
        migrations.DeleteModel(
            name='Zona',
        ),
    ]
