# Generated by Django 6.0.7 on 2026-07-17 22:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0017_remove_lotecultivo_zona_remove_tareaprogramada_zona_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivo',
            name='dias_para_tutorado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='fecha_trasplante',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='inicio_tutorado',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bloque',
            name='invernadero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='cultivos.invernadero'),
        ),
        migrations.AlterField(
            model_name='tareaprogramada',
            name='tipo_tarea',
            field=models.CharField(choices=[('SIEMBRA', 'Siembra'), ('RIEGO', 'Riego'), ('FUMIGACION', 'Fumigación'), ('FERTILIZACION', 'Fertilización'), ('PODA', 'Poda / Deshije'), ('TUTORADO', 'Tutorado / Amarre'), ('TRASPLANTE', 'Trasplante'), ('COSECHA', 'Cosecha')], max_length=50),
        ),
        migrations.CreateModel(
            name='Fumigacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aplicacion', models.DateTimeField(default=datetime.date(2026, 7, 17))),
                ('dosis', models.CharField(max_length=50)),
                ('gasto_agua', models.FloatField(help_text='Litros de agua totales preparados')),
                ('intervalo_seguridad', models.IntegerField(help_text='Días obligatorios que deben pasar antes de poder cosechar')),
                ('plaga_objetivo', models.CharField(max_length=100)),
                ('aplicador', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fumigaciones', to='cultivos.bloque')),
                ('compuesto_aplicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.insumo')),
            ],
        ),
    ]
