# Generated by Django 6.0.7 on 2026-07-23 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0017_remove_cultivo_inicio_tutorado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fumigacion',
            name='fecha_aplicacion',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 23, 5, 34, 32, 89233, tzinfo=datetime.timezone.utc)),
        ),
    ]
