# Generated by Django 6.0.7 on 2026-07-23 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0018_alter_fumigacion_fecha_aplicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fumigacion',
            name='fecha_aplicacion',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 23, 7, 55, 53, 981580, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='lotecultivo',
            name='id_lote',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
