# Generated by Django 6.0.7 on 2026-07-17 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0018_cultivo_dias_para_tutorado_cultivo_fecha_trasplante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fumigacion',
            name='fecha_aplicacion',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 17, 22, 30, 4, 285796, tzinfo=datetime.timezone.utc)),
        ),
    ]
