# Generated by Django 6.0.7 on 2026-07-17 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0019_alter_fumigacion_fecha_aplicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fumigacion',
            name='fecha_aplicacion',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 17, 22, 30, 32, 509292, tzinfo=datetime.timezone.utc)),
        ),
    ]
