# Generated by Django 6.0.7 on 2026-07-23 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0019_alter_fumigacion_fecha_aplicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fumigacion',
            name='fecha_aplicacion',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 23, 7, 57, 53, 762449, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='lotecultivo',
            name='fecha_plantacion',
            field=models.DateField(default=datetime.datetime(2026, 7, 23, 7, 57, 53, 759410, tzinfo=datetime.timezone.utc)),
        ),
    ]
