# Generated by Django 6.0.7 on 2026-07-23 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0020_alter_fumigacion_fecha_aplicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fumigacion',
            name='fecha_aplicacion',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 23, 8, 11, 36, 85955, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='lotecultivo',
            name='fecha_plantacion',
            field=models.DateField(default=datetime.datetime(2026, 7, 23, 8, 11, 36, 82905, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='lotecultivo',
            name='tipo_sustrato_sugerido',
            field=models.CharField(choices=[('FIBRA_COCO', 'Fibra de coco'), ('PERLITA', 'Perlita'), ('TEZONTLE', 'Tezontle'), ('VERMICULITA', 'Vermiculita'), ('LANA_ROCA', 'Lana de roca'), ('ARCILLA_EXPANDIDA', 'Arcilla expandida'), ('TURBA', 'Turba'), ('RAIZ_FLOTANTE', 'Sin sustrato')], default=''),
        ),
    ]
