# Generated by Django 6.0.7 on 2026-07-18 19:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0020_alter_fumigacion_fecha_aplicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoAgroquimicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoPlagas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comun', models.CharField(max_length=100)),
                ('nombre_cientifico', models.CharField(blank=True, max_length=100)),
                ('categoria', models.CharField(choices=[('INSECTO', 'insecto'), ('ACARO', 'ácaro'), ('HONGO', 'hongo'), ('BACTERIA', 'bacteria'), ('VIRUS', 'virus')], max_length=80)),
                ('descripcion_sintomas', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='cultivo',
            old_name='dias_para_primer_fumigacion',
            new_name='conductividad_electrica_optima',
        ),
        migrations.RemoveField(
            model_name='cultivo',
            name='frecuencia_fumigacion',
        ),
        migrations.RemoveField(
            model_name='lotecultivo',
            name='sistema_cultivo',
        ),
        migrations.AddField(
            model_name='cultivo',
            name='ph_optimo_max',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cultivo',
            name='ph_optimo_min',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cultivo',
            name='tiempo_espera_minutos',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cultivo',
            name='tiempo_riego_minutos',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cultivo',
            name='tipo_sustrato_sugerido',
            field=models.CharField(choices=[('FIBRA_COCO', 'fibra_coco'), ('PERLITA', 'perlita'), ('TEZONTLE', 'tezontle'), ('RAIZ_FLOTANTE', 'raiz_flotante')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='catalogoinsumos',
            name='tipo_insumo',
            field=models.CharField(choices=[('FERTILIZANTE', 'Fertilizante'), ('SEMILLA', 'Semilla'), ('SUSTRATO', 'Sustrato'), ('OTRO', 'Otro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='dias_para_primer_fertilizacion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='dias_para_tutorado',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='fecha_trasplante',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='frecuencia_cosecha',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='frecuencia_fertilizacion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='frecuencia_poda',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='frecuencia_riego',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='inicio_tutorado',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fumigacion',
            name='dosis',
            field=models.IntegerField(default=0, help_text='expresado en gramos o mililitros'),
        ),
        migrations.AlterField(
            model_name='fumigacion',
            name='fecha_aplicacion',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 18, 19, 48, 40, 138198, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.catalogoinsumos'),
        ),
        migrations.AlterField(
            model_name='lotecultivo',
            name='bloque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.bloque'),
        ),
        migrations.AlterField(
            model_name='lotecultivo',
            name='cama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.cama'),
        ),
        migrations.AlterField(
            model_name='lotecultivo',
            name='invernadero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.invernadero'),
        ),
        migrations.AlterField(
            model_name='tareaprogramada',
            name='tipo_tarea',
            field=models.CharField(choices=[('SIEMBRA', 'Siembra'), ('RIEGO', 'Riego'), ('FERTILIZACION', 'Fertilización'), ('PODA', 'Poda / Deshije'), ('TUTORADO', 'Tutorado / Amarre'), ('TRASPLANTE', 'Trasplante'), ('COSECHA', 'Cosecha')], max_length=50),
        ),
    ]
