# Generated by Django 6.0.7 on 2026-07-18 22:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0021_catalogoagroquimicos_catalogoplagas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotecultivo',
            name='estado',
        ),
        migrations.AddField(
            model_name='lotecultivo',
            name='actividad',
            field=models.CharField(choices=[('SIEMBRA', 'Siembra'), ('RIEGO', 'Riego'), ('FERTILIZACION', 'Fertilización'), ('PODA', 'Poda'), ('TUTORADO', 'Tutorado'), ('TRASPLANTE', 'Trasplante'), ('COSECHA', 'Cosecha')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='tipo_sustrato_sugerido',
            field=models.CharField(choices=[('FIBRA_COCO', 'Fibra de coco'), ('PERLITA', 'Perlita'), ('TEZONTLE', 'Tezontle'), ('VERMICULITA', 'Vermiculita'), ('LANA_ROCA', 'Lana de roca'), ('ARCILLA_EXPANDIDA', 'Arcilla expandida'), ('TURBA', 'Turba'), ('RAIZ_FLOTANTE', 'Sin sustrato')]),
        ),
        migrations.AlterField(
            model_name='fumigacion',
            name='fecha_aplicacion',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 18, 22, 33, 38, 417737, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tareaprogramada',
            name='lote_cultivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lote_cultivo', to='cultivos.lotecultivo'),
        ),
        migrations.AlterField(
            model_name='tareaprogramada',
            name='tipo_tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_tarea', to='cultivos.lotecultivo'),
        ),
    ]
