# Generated by Django 6.0.7 on 2026-07-21 23:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0022_remove_lotecultivo_estado_lotecultivo_actividad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fumigacion',
            name='fecha_aplicacion',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 21, 23, 16, 45, 911927, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='lotecultivo',
            name='plantilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantilla', to='cultivos.cultivo'),
        ),
    ]
