# Generated by Django 6.0.7 on 2026-07-22 00:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0023_alter_fumigacion_fecha_aplicacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultivo',
            name='tipo_sustrato_sugerido',
        ),
        migrations.AddField(
            model_name='cultivo',
            name='tipo_cultivo',
            field=models.CharField(choices=[('TIERRA', 'Tierra'), ('HIDROPONIA', 'Hidroponia'), ('MIXTO', 'Tierra e hidroponia')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lotecultivo',
            name='tipo_sustrato_sugerido',
            field=models.CharField(choices=[('FIBRA_COCO', 'Fibra de coco'), ('PERLITA', 'Perlita'), ('TEZONTLE', 'Tezontle'), ('VERMICULITA', 'Vermiculita'), ('LANA_ROCA', 'Lana de roca'), ('ARCILLA_EXPANDIDA', 'Arcilla expandida'), ('TURBA', 'Turba'), ('RAIZ_FLOTANTE', 'Sin sustrato')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fumigacion',
            name='fecha_aplicacion',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 22, 0, 15, 44, 852557, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='tipo',
            field=models.CharField(choices=[('FERTILIZANTE', 'Fertilizante'), ('SEMILLA', 'Semilla'), ('SUSTRATO', 'Sustrato'), ('OTRO', 'Otro')], default='-----', max_length=50),
        ),
        migrations.AlterField(
            model_name='lotecultivo',
            name='plantilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.cultivo'),
        ),
    ]
