# Generated by Django 6.0.7 on 2026-07-22 01:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0024_remove_cultivo_tipo_sustrato_sugerido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fumigacion',
            name='fecha_aplicacion',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 22, 1, 4, 35, 737873, tzinfo=datetime.timezone.utc)),
        ),
    ]
