# Generated by Django 6.0.7 on 2026-07-22 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0025_alter_fumigacion_fecha_aplicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fumigacion',
            name='fecha_aplicacion',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 22, 6, 20, 42, 996082, tzinfo=datetime.timezone.utc)),
        ),
    ]
