# Generated by Django 6.0.7 on 2026-07-22 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0026_alter_fumigacion_fecha_aplicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivo',
            name='ciclo_de_vida_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='conductividad_electrica_optima',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='dias_para_inicio_cosecha',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='dias_para_primer_fertilizacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='dias_para_primer_riego',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='dias_para_primera_poda',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='dias_para_tutorado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='fecha_trasplante',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='frecuencia_cosecha',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='frecuencia_fertilizacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='frecuencia_poda',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='frecuencia_riego',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='inicio_tutorado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='ph_optimo_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='ph_optimo_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='tiempo_espera_minutos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='tiempo_riego_minutos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fumigacion',
            name='fecha_aplicacion',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 22, 7, 35, 34, 89825, tzinfo=datetime.timezone.utc)),
        ),
    ]
