# Generated by Django 6.0.7 on 2026-07-22 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0027_alter_cultivo_ciclo_de_vida_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotecultivo',
            name='actividad',
        ),
        migrations.AlterField(
            model_name='fumigacion',
            name='fecha_aplicacion',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 22, 8, 0, 52, 220215, tzinfo=datetime.timezone.utc)),
        ),
    ]
